### ISSUE TITLE
Feature request: Add "auto" option to the toggle

### ISSUE THREAD

**Issue by showme032** [FaridZelli/Toggley#3]
Hello, after toggling between dark/light theme, automatic or "system theme - auto" which I normally use, needs to be manually turned back on. Is it possible to add that selection to the toggle, as it's a native firefox option?

**Comment by FaridZelli** [comment]
Hi, thank you for the suggestion.

I'd rather avoid introducing a 3rd toggle state or any optional features. However, I might be able to add "Switch to system theme" to the extension's context menu instead. This can be accessed by right clicking Toggley, or long pressing the icon on a touchscreen.

**Comment by showme032** [comment]
Ok, thanks for your answer!

**Comment by FaridZelli** [comment]
Added, expect an update soon 👍

![image](https://github.com/FaridZelli/Toggley/assets/82771409/b16d47e4-5cda-4383-929f-1811941ae0b4)

**Comment by FaridZelli** [comment]
Toggley 1.5 has been published, closing this issue as completed.

**Comment by showme032** [comment]
That was quick!
